### ISSUE TITLE
Add SSDs

### ISSUE THREAD

**Issue by Ocawesome101** [ShadowKatStudios/OpenSolidState#4]
The mod's name ("OpenSolidState") kind of implies that it adds SSDs, so why not actually do it?

**Comment by Ocawesome101** [comment]
Should be labeled as "enhancement" - I can't figure out how (or if I'm able) to label issues.

**Comment by lunaboards-dev** [comment]
tl;dr no

For the long answer, SSDs as you're probably thinking of (replacing the HDD) would break the balance of OC. So called "NAND Flash upgrades" (for tablets, uCs, drones, etc) are planned in release v1.1.0, and will come in 8K, 16K, and 32K variants. They'll probably show up as `drive` components. No managed filesystem.

Basically, the idea is, I don't want to break the balance of OC, thus why the current general purpose EEPROM are so limited. (Slow erase, slow write)
